# **PyTorch Basics: Tensors & Gradients**
Let's import the torch module to get started.

In [1]:
import torch

# **Tensors in Pytorch**
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [2]:
# Number
t1 = torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1,2,3])
t2

tensor([1, 2, 3])

In [6]:
# slightly more complex tensor
t3 = torch.tensor([[1,2,3],[2,3,4],[5,4,3]])
t3

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 4, 3]])

In [7]:
t4 = torch.tensor([1., 2, 3, 4])
t4

tensor([1., 2., 3., 4.])

In [8]:
# Matrix
t5 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t5

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
# 3-D Array
t6 = torch.tensor([
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   ])
t6

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [10]:
# Let ceheck the shape
t6.shape

torch.Size([2, 2, 3])

# **Tensor operations and gradients**

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(6.,requires_grad=True)

In [12]:
# Arithmetics operations
y = w*x+b
y

tensor(18., grad_fn=<AddBackward0>)

In [13]:
# compute derivatives
y.backward()

In [14]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# **Tensor Functions**

In [15]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42.)
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [16]:
tt3  = torch.tensor([[2.,3.],[4.,6.],[5.,8.]])

In [17]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((tt3, t6))
t7

tensor([[ 2.,  3.],
        [ 4.,  6.],
        [ 5.,  8.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [18]:
t8 = torch.sin(t7)

In [19]:
t8

tensor([[ 0.9093,  0.1411],
        [-0.7568, -0.2794],
        [-0.9589,  0.9894],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [20]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[ 0.9093,  0.1411],
         [-0.7568, -0.2794]],

        [[-0.9589,  0.9894],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# **Numpy & Tensors Conversion**

In [21]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [22]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [23]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [24]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# **Thank You!**