In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1TpaG1fYNCp9OCR-NY0YYe6Tld6xw9zbm')

     |████████████████████████████████| 71kB 4.8MB/s 


> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# PYTORCH: TENSORS EXAMPLES

PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let see it's mathematical implementations by using some PyTorch built-in functions :- 
  
- TORCH.BERNOULLI
- TORCH.NORMAL
- TORCH.BITWISE_NOT
- TORCH.CLAMP
- TORCH.ARGSORT

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - TORCH.BERNOULLI

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

The input tensor should be a tensor containing probabilities to be used for drawing the binary random number. Hence, all values in input have to be in the range: 0 and 1.

> **torch.bernoulli(input, *, generator=None, out=None) → Tensor**

In [3]:
# Example 1 - working (change this)
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
a

tensor([[0.8577, 0.8660, 0.0901],
        [0.0674, 0.7798, 0.0552],
        [0.4095, 0.1263, 0.1612]])

In [5]:
# it set 0 and 1 on the basis of probability of a matrix
torch.bernoulli(a)

tensor([[1., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

Explanation about example

In [7]:
# Example 2 - working
b = torch.ones(3, 6) # probability of drawing "1" is 1
torch.bernoulli(b)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Explanation about example

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.empty(3, 3).uniform_(5, 6) 
torch.bernoulli(c)

RuntimeError: ignored

The probability of matrix must be between 0 and 1 but here we can see that matrix c have probabilty between 5 and 6. So, it's an error. Here in error we can see the p_in will be `true` if prob of a number is between 0 and 1 but it's greater and set to `False` that's why error.

You can use it in classification problem to show your final results.

Let's save our work using Jovian before continuing.

In [11]:
!pip install jovian --upgrade --quiet

In [12]:
import jovian

In [13]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'

## Function 2 - TORCH.NORMAL

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

* The `mean` is a tensor with the mean of each output element’s normal distribution

* The `std` is a tensor with the standard deviation of each output element’s normal distribution

* The shapes of mean and std don’t need to match, but the total number of elements in each tensor need to be the same.

 >**torch.normal(mean, std, *, generator=None, out=None) → Tensor**

In [14]:
# Example 1 - working
# mean
mean = torch.arange(1., 11.)
# standard deviation
std = torch.arange(1,0,-0.1)
torch.normal(mean, std)

tensor([-0.4875,  0.7237,  1.9654,  4.0919,  4.2460,  5.6293,  7.1683,  7.9267,
         9.2859,  9.8148])

It return tensor of random numbers drawn from separate normal distributions by the  mean and standard deviation which is given by us.

In [15]:
# Example 2 - working
# mean
mean = 0.5
# standard deviation
std = torch.arange(1., 6.)
torch.normal(mean, std)

tensor([-0.4062,  0.7726, -1.0518, -7.0675,  4.7046])

Now the result is given by the size of std and mean is common for all five elements.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=2,std=3)

TypeError: ignored

Now this error ocurred because it needed one more argument that is size. If we give one more argument like  size=(1, 4) then it work perfectly. It doesn't know what should be the shape of output tensor that's why error.

It can be used when we want to generate some new values from a given mean and std.

In [23]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'

## Function 3 - TORCH.BITWISE_NOT

Computes the bitwise NOT of the given input tensor. The input tensor must be of integral or Boolean types. For bool tensors, it computes the logical NOT.

> **torch.bitwise_not(input, *, out=None) → Tensor**

In [24]:
# Example 1 - working
torch.bitwise_not(torch.tensor([-1, -2, 3], dtype=torch.int8))

tensor([ 0,  1, -4], dtype=torch.int8)

Explanation about example

In [26]:
# Example 2 - working
torch.bitwise_not(torch.tensor([True, False, 3, 4, 5], dtype=torch.int8))

tensor([-2, -1, -4, -5, -6], dtype=torch.int8)

Explanation about example

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
torch.bitwise_not(torch.tensor([-1., -2., 3.]))

RuntimeError: ignored

This operations can't be apply for floating points numbers.

This function can be used in image processing by taking care of floating points numbers.

In [29]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'

## Function 4 - TORCH.CLAMP

Clamp all elements in input into the range `[ min, max ]` and return a resulting tensor.

> **torch.clamp(input, min, max, *, out=None) → Tensor**

In [33]:
# Example 1 - working
a = torch.randn(4)
a

tensor([ 0.6463,  0.3681, -1.0105,  0.4550])

In [35]:
torch.clamp(a, min=-0.5, max=0.2)

tensor([ 0.2000,  0.2000, -0.5000,  0.2000])

Explanation about example

In [37]:
# Example 2 - working
b = torch.randn(5)
b

tensor([ 0.3676, -2.1249,  0.8019,  1.0089,  1.5268])

In [38]:
torch.clamp(b, min=0.1)

tensor([0.3676, 0.1000, 0.8019, 1.0089, 1.5268])

Explanation about example

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.randn(4)
c

tensor([-0.6863,  0.7623, -1.0074,  1.2440])

In [51]:
torch.clamp(c)

RuntimeError: ignored

It required atleast one argument min or max. Both must not be left `None`.

To clamp the value between given min and max number.



In [52]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'

## Function 5 - TORCH.ARGSORT

Returns the indices that sort a tensor along a given dimension in ascending order by value.

> **torch.argsort(input, dim=-1, descending=False) → LongTensor**

In [53]:
# Example 1 - working
a = torch.randn(4, 4)
a

tensor([[-1.7410, -0.3209, -1.4893, -1.4207],
        [-0.6450,  1.6361, -0.5672, -0.4403],
        [ 1.5960,  1.5749, -1.2086, -1.8681],
        [-1.3784,  0.2232, -1.1140,  1.2713]])

In [54]:
torch.argsort(a, dim=1)

tensor([[0, 2, 3, 1],
        [0, 2, 3, 1],
        [3, 2, 1, 0],
        [0, 2, 1, 3]])

Explanation about example

In [55]:
# Example 2 - working
b = torch.randn(5, 4)
b

tensor([[ 1.5664, -1.5824,  1.8326,  0.5473],
        [ 0.2952, -1.3079, -1.3203,  0.0868],
        [ 0.0532, -1.1134, -0.4420,  0.7908],
        [-0.1406,  0.0637, -0.5719,  0.2956],
        [ 1.9778,  1.1340, -0.0639,  2.2716]])

In [57]:
torch.argsort(b)

tensor([[1, 3, 0, 2],
        [2, 1, 3, 0],
        [1, 2, 0, 3],
        [2, 0, 1, 3],
        [2, 1, 0, 3]])

Explanation about example

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.randn(5, 8)
c

tensor([[ 0.5698, -0.0166, -0.8730,  0.9253,  0.5552,  1.9456, -1.6192,  0.4206],
        [-0.0482, -0.2650,  1.0987, -0.2075, -1.4154, -0.5969,  0.1385, -0.8387],
        [-0.5501,  0.8571,  0.5036, -0.7083,  1.1437,  0.7221, -1.0909, -0.2811],
        [ 0.4078,  0.0367, -0.6024, -0.1564, -0.4063, -0.5584,  0.4385,  0.0642],
        [-0.2326,  0.1298,  0.7839,  1.8494, -0.6862, -0.5726, -0.3395, -0.1940]])

In [65]:
torch.argsort(c, dim=10)

IndexError: ignored

If you don't give any dimension it doesn't have any problem but if you give it should be in the specified range.

**Expected to be in range of [-2, 1]**

The indices that sort a tensor along a given dimension in ascending order by value. This is the second value returned by `torch.sort().`

In [66]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'

## Conclusion

In this notebook we demonstrate the use of 5 tensor functions that are useful. To play around with more such function you can visit on <a href='https://pytorch.org/docs/stable/torch.html'>PyTorch docs.</a>

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [72]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kishanyadav3223/01-tensor-operations


'https://jovian.ai/kishanyadav3223/01-tensor-operations'